name: CI

on:
#    pull_request: ~
    push:
        branches:
            - 'version/*'

jobs:
    cs:
        name: Coding Style
        runs-on: ubuntu-latest
        steps:
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2

            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Install ecs
                run: cd tools/ecs && composer update --no-interaction --no-suggest

            -   name: Run the CS fixer
                run: composer cs-fixer
