on:
    push:
        branches:
            - main

jobs:
    release-on-merge:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        steps:
            -   uses: dexwritescode/release-on-merge-action@v1
